name: Deploy to SAP BTP

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-to-sap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to SAP BTP
        uses: citizen-of-cosmos/cf-cli-action@master
        with:
          cf_api: ${{ secrets.CF_API_URL }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          command: push khallaoui-sap-app -p . -m 64M --random-route -b staticfile_buildpack